server:
    port: 9999

spring:
  datasource:
    username: sqlserver
    password: LY280018ly!!!
    url: jdbc:mysql://sqlserver.mysql.database.azure.com:3306/gkvr_system
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.scu: debug
