server:
    port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gkvr_system
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.scu: debug
